### ISSUE TITLE
User can see their car 

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create html document
- [x] create styles.css sheet
- [x] set the background to a green color using css
- [x] add the car using an img tag
