### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/driving-game#2]
### 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create a main.js 
- [x] link the main.js page to index.html
- [x] query the DOM for the car
- [x] add a keydown event with the arrow keys
