### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] create a new event handler to start the car
- [x] use the keydown event on the space button 
- [x] when space is pressed the car will go right 16px
- [x] use setInterval function
- [x] within the callback function set the initial position to 0 and when the event is triggered it increments the pixels .
